### ISSUE TITLE
when sw.js change, lifecycle event 'activate' delete cache include it's name?

### ISSUE THREAD

**Issue by AsceticBoy** [JimmyVV/PWA-cookbook#1]
Hello Jimmy!
I pay attention to you about `PWA` when D2 conference because i practicing this `service-worker` in own project.
## What problem
I see the `PWA-cookbook/sw.js` about `activate` event, you delete old cache use if `CURRENT_CACHES.include`, but i think never matched `key` for `CURRENT_CACHES` should be delete
example [google example](https://googlechrome.github.io/samples/service-worker/prefetch/service-worker.js) what you think about it ?

**Thanks for you provide `PWA` introduction. I get more help from it.** 😀

**Comment by JimmyVV** [comment]
yeah, the strategy is not fixed. you can customize youself plan, you know, like:
```
presistent
often
selfdom
```
the introduction is a little out of date, you can refer to my blog villainhr.com for more information.

**Comment by AsceticBoy** [comment]
Thank you very much !! I already watched you bolg.😀
